import 'package:flutter/material.dart';
import 'package:hooks_riverpod/hooks_riverpod.dart';
import 'package:hooks_riverpod/legacy.dart';
import '../../../core/storage/hive_service.dart';
import '../data/models/category_model.dart';
import '../data/models/expense_model.dart';
import '../data/models/income_model.dart';
import '../data/repositories/finance_repository_impl.dart';
import '../domain/repositories/finance_repository.dart';

// ===== UI STATE (Presentation Layer) =====
// This represents the TEMPORARY state while user fills the form
class AddTransactionState {
  final CategoryModel? selectedCategory;
  final String amount;
  final String note;
  final DateTime selectedDate;
  final TimeOfDay selectedTime;
  final bool isLoading;
  final String? errorMessage;

  AddTransactionState({
    this.selectedCategory,
    required this.amount,
    required this.note,
    required this.selectedDate,
    required this.selectedTime,
    this.isLoading = false,
    this.errorMessage,
  });

  factory AddTransactionState.initial() {
    return AddTransactionState(
      amount: "",
      note: "",
      selectedDate: DateTime.now(),
      selectedTime: TimeOfDay.now(),
    );
  }

  // Validation - UI Logic
  bool get isValid {
    final amountValue = double.tryParse(amount);
    return selectedCategory != null &&
        amountValue != null &&
        amountValue > 0;
  }

  String? get validationError {
    if (selectedCategory == null) return "Please select a category";
    final amountValue = double.tryParse(amount);
    if (amountValue == null || amountValue <= 0) return "Please enter a valid amount";
    return null;
  }

  AddTransactionState copyWith({
    CategoryModel? selectedCategory,
    String? amount,
    String? note,
    DateTime? selectedDate,
    TimeOfDay? selectedTime,
    bool? isLoading,
    String? errorMessage,
  }) {
    return AddTransactionState(
      selectedCategory: selectedCategory ?? this.selectedCategory,
      amount: amount ?? this.amount,
      note: note ?? this.note,
      selectedDate: selectedDate ?? this.selectedDate,
      selectedTime: selectedTime ?? this.selectedTime,
      isLoading: isLoading ?? this.isLoading,
      errorMessage: errorMessage,
    );
  }
}

// ===== VIEW MODEL (Presentation Layer) =====
// Handles UI logic and coordinates with domain layer
class AddTransactionNotifier extends StateNotifier<AddTransactionState> {
  final Ref ref;
  final TransactionType transactionType;

  AddTransactionNotifier(this.ref, this.transactionType)
      : super(AddTransactionState.initial());

  // UI Actions
  void setCategory(CategoryModel category) {
    state = state.copyWith(selectedCategory: category);
  }

  void setAmount(String amount) {
    state = state.copyWith(amount: amount);
  }

  void setNote(String note) {
    state = state.copyWith(note: note);
  }

  void setDate(DateTime date) {
    state = state.copyWith(selectedDate: date);
  }

  void setTime(TimeOfDay time) {
    state = state.copyWith(selectedTime: time);
  }

  void reset() {
    state = AddTransactionState.initial();
  }

  // Business Logic - Convert UI state to Domain model and save
  Future<bool> saveTransaction() async {
    final userId = HiveService().userId; //
print('user id ${userId}');
    if (userId == null) {
      debugPrint("❌ Error: No User ID found in Local Storage. Please login.");
      return false;
    }
    print('transaction type  and data ${transactionType} & ${state.isValid}');
    if (!state.isValid) {
      state = state.copyWith(errorMessage: state.validationError);
      return false;
    }


    state = state.copyWith(isLoading: true, errorMessage: null);

    try {
      final repository = ref.read(FinanceRepositoryProvide);
      final amount = double.parse(state.amount);
print('amount $amount');
      // Combine date and time
      final dateTime = DateTime(
        state.selectedDate.year,
        state.selectedDate.month,
        state.selectedDate.day,
        state.selectedTime.hour,
        state.selectedTime.minute,
      );

      if (transactionType == TransactionType.income) {
        // Convert UI state → Domain model
        final income = IncomeModel(
          id: '', // Will be generated by Appwrite
          userId: userId,
          amount: amount,
          categoryId: state.selectedCategory!.id,
          source: state.selectedCategory!.name,
          date: dateTime,
          isRecurring: false,
          note: state.note.isEmpty ? null : state.note,
        );

        await repository.addIncome(income);
      } else {
        // Convert UI state → Domain model
        final expense = ExpenseModel(
          id: '', // Will be generated by Appwrite
          userId: userId,
          amount: amount,
          categoryId: state.selectedCategory!.id,
          paymentMethod: 'Cash', // You might want to add this to UI state
          date: dateTime,
          note: state.note.isEmpty ? null : state.note,
        );

        await repository.addExpense(expense);
      }

      state = state.copyWith(isLoading: false);
      // reset(); // Clear form after successful save
      return true;

    } catch (e) {
      print('❌ Repository Error: $e'); // Add this line
      state = state.copyWith(
        isLoading: false,
        errorMessage: 'Failed to save transaction: ${e.toString()}',
      );
      return false;
    }
  }
}

// Provider
final addTransactionProvider =
StateNotifierProvider.autoDispose.family<
    AddTransactionNotifier,
    AddTransactionState,
    TransactionType>((ref, type) {
  return AddTransactionNotifier(ref, type);
});
