import 'package:flutter/cupertino.dart';
import 'package:hooks_riverpod/hooks_riverpod.dart';
import 'package:hooks_riverpod/legacy.dart';

import '../../auth/presentation/states/auth_state.dart';
import '../data/models/finance_enums.dart';
import '../data/models/goal_model.dart';
import '../domain/repositories/finance_repository.dart';
import '../../auth/presentation/providers/auth_provider.dart';
import 'finance_provider.dart';

// --- State Class ---
class GoalsState {
  final List<GoalModel> goals;
  final bool isLoading;

  GoalsState({
    required this.goals,
    this.isLoading = false,
  });

  // FIX 1: Add getters so the View can access totals
  double get totalSaved => goals.fold(0.0, (sum, item) => sum + item.currentAmount);
  double get totalTarget => goals.fold(0.0, (sum, item) => sum + item.targetAmount);

  GoalsState copyWith({List<GoalModel>? goals, bool? isLoading}) {
    return GoalsState(
      goals: goals ?? this.goals,
      isLoading: isLoading ?? this.isLoading,
    );
  }
}

// --- Notifier Class ---
class GoalsNotifier extends StateNotifier<GoalsState> {
  final FinanceRepository _repository;
  final String? _userId;

  GoalsNotifier(this._repository, this._userId) : super(GoalsState(goals: [])) {
    if (_userId != null) {
      fetchGoals();
    }
  }

  Future<void> fetchGoals() async {
    if (_userId == null) {
      debugPrint("fetchGoals aborted: userId is null");
      return;
    }
    state = state.copyWith(isLoading: true);
    try {
      final goals = await _repository.getGoals(_userId!);
      debugPrint("fetchGoals success: fetched ${goals.length} goals");
      state = state.copyWith(goals: goals, isLoading: false);
    } catch (e) {
      debugPrint("Error fetching goals: $e");
      state = state.copyWith(isLoading: false);
    }
  }

  Future<void> addGoal({
    required String title,
    required double target,
    required DateTime deadline,
    required String categoryId, // Changed from GoalCategory enum

  }) async {
    if (_userId == null) throw Exception("User not authenticated");

    final newGoal = GoalModel(
      id: '', // Generated by Appwrite
      userId: _userId!,
      title: title,
      targetAmount: target,
      currentAmount: 0.0,
      deadline: deadline,
      status: GoalStatus.active,
      categoryId: categoryId, // Save the string ID

    );

    try {
      await _repository.addGoal(newGoal);
      await fetchGoals();
    } catch (e) {
      debugPrint("Error adding goal: $e");
      rethrow;
    }
  }

  Future<void> updateGoal(GoalModel updatedGoal) async {
    try {
      await _repository.updateGoal(updatedGoal);
      await fetchGoals();
    } catch (e) {
      debugPrint("Error updating goal: $e");
      rethrow;
    }
  }

  Future<void> deleteGoal(String id) async {
    try {
      await _repository.deleteGoal(id);
      await fetchGoals();
    } catch (e) {
      debugPrint("Error deleting goal: $e");
      rethrow;
    }
  }
}

// --- Provider Definition ---
// Ensure 'financeRepositoryProvider' is defined in your DI
final goalsProvider = StateNotifierProvider<GoalsNotifier, GoalsState>((ref) {
  final repo = ref.watch(financeRepositoryProvider);
  // Watch auth state to get the current user ID
  final authState = ref.watch(authProvider);
  final userId = authState.maybeWhen(
    authenticated: (user) => user.id,
    orElse: () => null,
  );

  return GoalsNotifier(repo, userId);
});